language: php

## Run on container environment
sudo: false
    
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm
  
before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then echo 'opcache.enable=1' >> /etc/hhvm/php.ini; fi
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then echo 'opcache.enable_cli=1' >> /etc/hhvm/php.ini; fi
  - composer self-update
  - composer update -o --prefer-source

script:
  - vendor/bin/php-cs-fixer fix --dry-run -vv
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
