## Run on container environment
sudo: false

language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  matrix:
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - DEPENDENCIES=""

matrix:
  allow_failures:
    - php: hhvm
  
before_script:
  - composer self-update
  - composer update -o --prefer-source $DEPENDENCIES

script:
  - vendor/bin/phpunit --testsuite IntegrationTests --coverage-clover ./clover.xml
  - vendor/bin/php-cs-fixer fix --dry-run -vv

after_script:
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover ./clover.xml; fi
